---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-prepare-get
  - name: pcfawsops-terraform-state-get
outputs:
  - name: pcfawsops-terraform-state-put
run:
  path: aws-prepare-get/ci/scripts/destroy-aws.sh
