---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-prepare-get
  - name: pcfawsops-terraform-state-get
  - name: ert-concourse
outputs:
  - name: pcfawsops-terraform-state-put
params:
  TF_VAR_aws_access_key:
  TF_VAR_aws_secret_key:
  TF_VAR_aws_key_name:
  TF_VAR_rds_db_username:
  TF_VAR_rds_db_password:
  TF_VAR_environment:
  TF_VAR_opsman_ami:
  TF_VAR_amis_nat:
  TF_VAR_aws_region:
  TF_VAR_az1:
  TF_VAR_az2:
  TF_VAR_az3:
  TF_VAR_using_private_zone: true
  pcf_ert_domain:
  ert_ssl_cert:
  ert_ssl_key:
run:
  path: aws-prepare-get/ci/scripts/prepare-aws.sh
