---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-prepare-get
  - name: pcfawsops-terraform-state-get
params:
  PEM:
  ERT_DOMAIN:
run:
  path: aws-prepare-get/ci/scripts/prepare-rds.sh
