groups:
- name: all
  jobs:
  - aws-pcf-prepare
  - config-opsman
  - aws-pcf-destroy
- name: prepare
  jobs:
  - aws-pcf-prepare
- name: config-opsman
  jobs:
  - config-opsman
- name: config-director
  jobs:
  - config-director
- name: destroy
  jobs:
  - aws-pcf-destroy

resources:
- name: aws-prepare-get
  type: git
  source:
    branch: master
    uri: https://github.com/c0-ops/aws-concourse.git
- name: pcfawsops-terraform-state-put
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{TF_VAR_aws_access_key}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OUTPUT_BUCKET}}
    versioned_file: terraform.tfstate
- name: pcfawsops-terraform-state-get
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{TF_VAR_aws_access_key}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OUTPUT_BUCKET}}
    versioned_file: terraform.tfstate
- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om

jobs:
- name: aws-pcf-prepare
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: pcfawsops-terraform-state-get
  - task: aws-pcf-prepare
    file: aws-prepare-get/ci/tasks/prepare-aws.yml
    params:
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_rds_db_username: {{TF_VAR_rds_db_username}}
      TF_VAR_rds_db_password: {{TF_VAR_rds_db_password}}
      TF_VAR_environment: {{TF_VAR_environment}}
      TF_VAR_opsman_ami: {{TF_VAR_opsman_ami}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
  - put: pcfawsops-terraform-state-put
    params:
      file: pcfawsops-terraform-state-put/terraform.tfstate

- name: config-opsman
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: tool-om
  - task: config-opsman
    file: aws-prepare-get/ci/tasks/config-opsman.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

- name: config-director
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: pcfawsops-terraform-state-get
  - task: config-director
    file: aws-prepare-get/ci/tasks/config-director.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AWS_TEMPLATE: "c0-aws-base"
      AWS_KEY_NAME: {{TF_VAR_aws_key_name}}
      AWS_REGION: {{TF_VAR_aws_region}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      IP_PREFIX: {{IP_PREFIX}}

- name: aws-pcf-destroy
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: pcfawsops-terraform-state-get
  - task: aws-pcf-destroy
    file: aws-prepare-get/ci/tasks/destroy-aws.yml
    params:
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_rds_db_username: {{TF_VAR_rds_db_username}}
      TF_VAR_rds_db_password: {{TF_VAR_rds_db_password}}
      TF_VAR_environment: {{TF_VAR_environment}}
      TF_VAR_opsman_ami: {{TF_VAR_opsman_ami}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
  - put: pcfawsops-terraform-state-put
    params:
      file: pcfawsops-terraform-state-put/terraform.tfstate
