groups:
- name: all
  jobs:
  - aws-pcf-prepare
  - config-opsman
  - config-director
  - upload-ert
  - deploy-ert
  - aws-pcf-destroy
- name: prepare
  jobs:
  - aws-pcf-prepare
- name: config-opsman
  jobs:
  - config-opsman
- name: config-director
  jobs:
  - config-director
- name: upload-ert
  jobs:
  - upload-ert
- name: deploy-ert
  jobs:
  - deploy-ert
- name: destroy
  jobs:
  - aws-pcf-destroy

resource_types:

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: v0.26.1

resources:
- name: aws-prepare-get
  type: git
  source:
    branch: master
    uri: https://github.com/c0-ops/aws-concourse.git
- name: pcfawsops-terraform-state-put
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{TF_VAR_aws_access_key}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OUTPUT_BUCKET}}
    versioned_file: terraform.tfstate
- name: pcfawsops-terraform-state-get
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{TF_VAR_aws_access_key}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OUTPUT_BUCKET}}
    versioned_file: terraform.tfstate
- name: tool-om-beta
  type: github-release
  source:
    user: c0-ops
    repository: om
- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
- name: pivnet-elastic-runtime
  type: pivnet
  check_every: 4h
  source:
    api_token: {{PIVNET_TOKEN}}
    product_slug: elastic-runtime
    product_version: 1\.8\..*
    sort_by: semver

jobs:
- name: aws-pcf-prepare
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: pcfawsops-terraform-state-get
  - task: aws-pcf-prepare
    file: aws-prepare-get/ci/tasks/prepare-aws.yml
    params:
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_rds_db_username: {{TF_VAR_rds_db_username}}
      TF_VAR_rds_db_password: {{TF_VAR_rds_db_password}}
      TF_VAR_environment: {{TF_VAR_environment}}
      TF_VAR_opsman_ami: {{TF_VAR_opsman_ami}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
  - put: pcfawsops-terraform-state-put
    params:
      file: pcfawsops-terraform-state-put/terraform.tfstate

- name: config-opsman
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: tool-om
  - task: config-opsman
    file: aws-prepare-get/ci/tasks/config-opsman.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

- name: config-director
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: pcfawsops-terraform-state-get
    - get: tool-om
    - get: tool-om-beta
  - task: config-director
    file: aws-prepare-get/ci/tasks/config-director.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AWS_TEMPLATE: "c0-aws-base"
      AWS_KEY_NAME: {{TF_VAR_aws_key_name}}
      PEM: {{PEM}}
      AWS_REGION: {{TF_VAR_aws_region}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      IP_PREFIX: {{IP_PREFIX}}

###########################
## Job - Upload ERT      ##
###########################
- name: upload-ert
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: aws-prepare-get
      trigger: true
      passed: [config-director]
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - "om-linux"
  - task: upload-ert
    file: aws-prepare-get/ci/tasks/upload-ert.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

###########################
## Job - Deploy ERT      ##
###########################
- name: deploy-ert
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: aws-prepare-get
      trigger: true
      passed: [upload-ert]
    - get: tool-om
      params:
        globs:
        - "om-linux"
  - task: deploy-ert
    file: aws-prepare-get/ci/tasks/deploy-ert.yml
    params:
      ERT_SSL_CERT: {{ERT_SSL_CERT}}
      ERT_SSL_KEY: {{ERT_SSL_KEY}}
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AWS_TEMPLATE: "c0-aws-base"
      S3_ENDPOINT: {{S3_ENDPOINT}}
      SYSLOG_HOST: {{SYSLOG_HOST}}

- name: aws-pcf-destroy
  serial: true
  plan:
  - aggregate:
    - get: aws-prepare-get
    - get: pcfawsops-terraform-state-get
  - task: aws-pcf-destroy
    file: aws-prepare-get/ci/tasks/destroy-aws.yml
    params:
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_rds_db_username: {{TF_VAR_rds_db_username}}
      TF_VAR_rds_db_password: {{TF_VAR_rds_db_password}}
      TF_VAR_environment: {{TF_VAR_environment}}
      TF_VAR_opsman_ami: {{TF_VAR_opsman_ami}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
  - put: pcfawsops-terraform-state-put
    params:
      file: pcfawsops-terraform-state-put/terraform.tfstate
